apiVersion: v1
kind: Service
metadata:
  name: react-redux-app
  labels:
    run: react-redux-app
spec:
  ports:
  - port: 9000
    targetPort: 4100
  selector:
    run: react-redux-app
  type: LoadBalancer